In [1]:
conda install pytorch torchvision -c pytorch

Retrieving notices: ...working... done

Note: you may need to restart the kernel to use updated packages.


Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000237790E1B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /pkgs/r/notices.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000237790E1150>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /pkgs/main/notices.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023778F22C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /pytorch/notices.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionErr

In [3]:
import torch
print(torch.cuda.is_available())
print(torch.rand(2,2))

ModuleNotFoundError: No module named 'torch'

In [7]:
# Load library
import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],
[2],
[3]])

In [9]:
vector_row

array([1, 2, 3])

In [11]:
vector_column

array([[1],
       [2],
       [3]])

In [13]:
# Load libraries
import numpy as np
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
[0, 1],
[3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [15]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

In [17]:
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [19]:
print(matrix_sparse)


  (1, 1)	1
  (2, 0)	3
